# TCL File Generated by Component Editor 13.0
# Mon May 14 23:44:57 BRT 2018
# DO NOT MODIFY


# 
# countBits "countBits" v1.0
# Rafael 2018.05.14.23:44:57
# Contador de bits
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module countBits
# 
set_module_property DESCRIPTION "Contador de bits"
set_module_property NAME countBits
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Component"
set_module_property AUTHOR Rafael
set_module_property DISPLAY_NAME countBits
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL toplevel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file toplevel.vhd VHDL PATH ../toplevel/toplevel.vhd TOP_LEVEL_FILE
add_fileset_file count8bits.vhd VHDL PATH ../count8bits/count8bits.vhd
add_fileset_file countBits0.vhd VHDL PATH ../countBits0/countBits0.vhd
add_fileset_file countBits1.vhd VHDL PATH ../countBits1/countBits1.vhd
add_fileset_file register16bits.vhd VHDL PATH ../register16bits/register16bits.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL toplevel
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file toplevel.vhd VHDL PATH ../toplevel/toplevel.vhd
add_fileset_file count8bits.vhd VHDL PATH ../count8bits/count8bits.vhd
add_fileset_file countBits0.vhd VHDL PATH ../countBits0/countBits0.vhd
add_fileset_file countBits1.vhd VHDL PATH ../countBits1/countBits1.vhd
add_fileset_file register16bits.vhd VHDL PATH ../register16bits/register16bits.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write_bus writedata Input 16
add_interface_port avalon_slave_0 read_bus readdata Output 16
add_interface_port avalon_slave_0 write_en write Input 1
add_interface_port avalon_slave_0 read_en read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset_n Input 1

